#!/bin/sh
# Generated by `codeyam-editor editor devcontainer-setup`. Runs each time
# this codespace's window connects (postAttachCommand): waits for the
# CodeYam Editor, then prints the link to open it.

port=14199
url="https://$CODESPACE_NAME-$port.$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN"
rule='=================================================='

echo 'Waiting for the CodeYam Editor to start...'
i=0
until curl -s -o /dev/null --max-time 2 "http://127.0.0.1:$port/"; do
  i=$((i + 1))
  if [ "$i" -ge 300 ]; then
    echo 'The CodeYam Editor did not start. See .codeyam/logs/codespaces-editor.log'
    exit 0
  fi
  sleep 2
done

printf '\n%s\n  CodeYam Editor is ready. Open it here (Cmd/Ctrl+click):\n\n  %s\n%s\n\n' \
  "$rule" "$url" "$rule"

# Opens a tab on its own once pop-ups are allowed for this site.
if [ -n "${BROWSER:-}" ]; then
  "$BROWSER" "$url" > /dev/null 2>&1
fi
exit 0
